name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Makefile Tests
        run: |
          make
          make clean
          make re
          make fclean
      - name: Lib Compilation
        run: make
      - name: Cleaning repository
        run: make fclean
      - name: Testing repository
        run: make tests_run
      
