name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    container: epitechcontent/epitest-docker:latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Lib Compilation
        run: make
      - name: Cleaning repository
        run: make clean
      - name: Recompile rule
        run: make re
      - name: Full Clean repository
        run: make fclean
      - name: Running tests on Lib
        run: make tests_run